spring.application.name=programming-quotes

spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.request.timeout=10s

cassandra.migration.enabled=true
cassandra.migration.keyspace=quotes
cassandra.migration.location=classpath:db/migration
